Repository DeveloperAcademy-YOLO/ProjectYOLO, pull requests merged in 2022-12, with the labels that each got.

#380 Fix/delete permission check/#379
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
Labels: bug

#384 Feature/addthe gift paper view controller/#350
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardCreateViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/GiftPaper/GiftPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/Other/GiftPaper/GiftPaperViewModel.swift
Labels: Feature

#383 Refactor/permission profile image/#382
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
Labels: refactor

#386 Feature/Add hotfix/#385
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTemplateCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: bug

#388 Design/adjust color for darkmode/#372
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/GiftPaper/GiftPaperViewController.swift
Labels: design

#390 Fix/insert bug/#389
  RollingPaper/RollingPaper/Managers/TimeFlowManager.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageClosedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageOpenedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/GiftStorage/GiftStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
Labels: bug, Feature, refactor

#395 Feature/change sidebar categories title and icon/#394
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/GiftStorage/GiftStorageViewModel.swift
Labels: Feature

#398 Design/change app setting view color/#396
  RollingPaper/RollingPaper/Assets.xcassets/AccentColor.colorset/Contents.json
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
Labels: design

#402 Feature/ContextMenu deadline/#401
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/CardsInPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature

#393 Feature/cameraimage&photoimage alert sticker/#392
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerToggleOff.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerToggleOff.imageset/StickerToggleOff.svg
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerToggleOn.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerToggleOn.imageset/StickerToggleOn.svg
  RollingPaper/RollingPaper/Extensions/UNUserNotificationCenter+Extensions.swift
  RollingPaper/RollingPaper/Utilities/DynamicLinks+Funcs.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardCreateViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardResultViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/GiftPaper/GiftPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/BlurredViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerDiscriptionBalloon.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/Other/Card/CardViewModel.swift
Labels: bug, Feature, design

#406 Refactor/indexCardPath_Change/#403
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/CardsInPaperViewController.swift
Labels: refactor

#407 Design/applogo change/#405
  RollingPaper/RollingPaper/Assets.xcassets/AccentColor.colorset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/AppIcon.appiconset/1024.png
  RollingPaper/RollingPaper/Assets.xcassets/AppIcon.appiconset/App Icons.png
  RollingPaper/RollingPaper/Assets.xcassets/AppIcon.appiconset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Sticker_Close.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Sticker_Close.imageset/close@3x 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Sticker_Flip.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Sticker_Flip.imageset/Flip@3x 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Sticker_Rotate.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Sticker_Rotate.imageset/Rotate@3x.png
  RollingPaper/RollingPaper/Assets.xcassets/Interface/TimerTapBalloon/TimerTapBalloon.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Rectangle_black 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Rectangle_black 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Rectangle_black.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Rectangle_light_pumpkin 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Rectangle_light_pumpkin 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Rectangle_light_pumpkin.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Rectangle_pumpkin 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Rectangle_pumpkin 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Rectangle_pumpkin.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Rectangle_red 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Rectangle_red 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Rectangle_red.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Rectangle 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Rectangle 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_yellow.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_yellow.imageset/Rectangle_yellow 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_yellow.imageset/Rectangle_yellow 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_yellow.imageset/Rectangle_yellow.png
  RollingPaper/RollingPaper/Assets.xcassets/logo.imageset/App Icons.png
  RollingPaper/RollingPaper/Assets.xcassets/logo.imageset/AppIcon_120.pdf
  RollingPaper/RollingPaper/Assets.xcassets/logo.imageset/Contents.json
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/GiftPaper/GiftPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/CardsInPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: design
