Repository DeveloperAcademy-YOLO/ProjectYOLO, pull requests merged in 2022-11, with the labels that each got.

#199 Design/change paper thumbnail/#194
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
Labels: design

#207 Feat/improvement based on halloween user test/#200
  .github/workflows/CI_dev.yml
  .gitignore
  RollingPaper/Podfile
  RollingPaper/Podfile.lock
  RollingPaper/Pods/Manifest.lock
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcworkspace/xcshareddata/xcschemes/RollingPaper.xcscheme
  RollingPaper/RollingPaper/Controllers/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/Controllers/TimerOfPaperViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/GoogleService-Info.plist
Labels: bug, Feature, design, refactor

#210 [feat] #209 dev as appStore
  README.md
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
Labels: Feature

#214 Documentation/1st sprint readme/#211
  README.md
Labels: documentation

#216 [refactoring] #215 foldering
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/AppDelegate.swift
  RollingPaper/RollingPaper/Components/SignUpTextField.swift
  RollingPaper/RollingPaper/Components/UILabel+Padding.swift
  RollingPaper/RollingPaper/Controllers/MainViewController.swift
  RollingPaper/RollingPaper/Extensions/Notification.Name+Extension.swift
  RollingPaper/RollingPaper/Extensions/UIApplication+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIButton+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIColor+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIControl+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIFont+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIImage+Extension.swift
  RollingPaper/RollingPaper/Extensions/UINavigationController+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIView+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UNUserNotificationCenter+Extensions.swift
  RollingPaper/RollingPaper/Resources/Combine+Extensions.swift
  RollingPaper/RollingPaper/SceneDelegate.swift
  RollingPaper/RollingPaper/Utilities/DynamicLinks+Funcs.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignUpViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CameraCustomPicker.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardResultViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerOfPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperTemplateSelectViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SettingScreenViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SignInViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SignUpViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Sidebar/SidebarViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Other/Card/CardViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Other/WrittenPaper/WrittenPaperViewModel.swift
Labels: refactor

#220 Refactoring/Dev-to-Main/#217
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/AppDelegate.swift
  RollingPaper/RollingPaper/Components/SignUpTextField.swift
  RollingPaper/RollingPaper/Components/UILabel+Padding.swift
  RollingPaper/RollingPaper/Controllers/MainViewController.swift
  RollingPaper/RollingPaper/Extensions/Notification.Name+Extension.swift
  RollingPaper/RollingPaper/Extensions/UIApplication+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIButton+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIColor+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIControl+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIFont+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIImage+Extension.swift
  RollingPaper/RollingPaper/Extensions/UINavigationController+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UIView+Extensions.swift
  RollingPaper/RollingPaper/Extensions/UNUserNotificationCenter+Extensions.swift
  RollingPaper/RollingPaper/Resources/Combine+Extensions.swift
  RollingPaper/RollingPaper/SceneDelegate.swift
  RollingPaper/RollingPaper/Utilities/DynamicLinks+Funcs.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignUpViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CameraCustomPicker.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardResultViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerOfPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperTemplateSelectViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SettingScreenViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SignInViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SignUpViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Sidebar/SidebarViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Other/Card/CardViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Other/WrittenPaper/WrittenPaperViewModel.swift
Labels: refactor

#225 Feature/limit paper title length ver2/#221
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
Labels: Feature

#226 Bug/fix card detail view corner radius/#203
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewModels/Other/Card/CardViewModel.swift
Labels: bug

#233 Refactor/codeconventionforsigninandsignup/#231
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Components/SignUpTextField.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignUpViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SignInViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SignUpViewModel.swift
Labels: refactor

#237 Feat/magnified card view revision/#236
  RollingPaper/.swiftlint.yml
  RollingPaper/RollingPaper/AppDelegate.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature, design

#247 [refactor] #245 refactor code
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerOfPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: refactor

#249 Feature/make time picker/#243
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperSettingViewModel.swift
Labels: Feature

#253 Feature/spinnerinsidesignviews/#244
  RollingPaper/RollingPaper/Assets.xcassets/AppIcon.appiconset/1024.png
  RollingPaper/RollingPaper/Assets.xcassets/AppIcon.appiconset/AppIcon_img.png
  RollingPaper/RollingPaper/Assets.xcassets/AppIcon.appiconset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/logo.imageset/AppIcon_120.pdf
  RollingPaper/RollingPaper/Assets.xcassets/logo.imageset/Contents.json
  RollingPaper/RollingPaper/Components/SignUpTextField.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignUpViewController.swift
Labels: Feature

#254 Feature/change sidebar view/#230
  RollingPaper/RollingPaper/Models/CategoryModel.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
Labels: Feature, refactor

#257 Feature/context menu card/#240
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature, refactor

#242 Fix/change leading in collection view/#232
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageClosedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageCollectionHeader.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageFlowLayout.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageLength.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageOpenedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
Labels: bug

#258 Feature/card create step3 renewal/#246
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Other/Card/BackgroundButtonViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CameraCustomPickerController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardCreateViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardResultViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/StickerCollectionViewCell.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/Other/Card/CardViewModel.swift
Labels: Feature

#263 Feature/handle timer/#251
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Components/TimerView.swift
  RollingPaper/RollingPaper/Extensions/String+Extensions.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageOpenedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperSettingViewModel.swift
Labels: Feature, design

#267 Feature/pinch gesture sticker/#266
  RollingPaper/Pods/StickerView/StickerView/StickerView.swift
  RollingPaper/RollingPaper/Assets.xcassets/Interface/MenuIcon/StickerAdjustIcons/Close.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Group 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Group 3.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Group 4.png
Labels: Feature

#270 Fix/user photos remaining when logged out/#255 #256
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
Labels: bug

#271 Feature/context menu UI revise/#259
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/SettingScreenViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Other/WrittenPaper/WrittenPaperViewModel.swift
Labels: Feature

#284 Feature/application setting screen/#264
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Models/AppSettingModels.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/AppSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Sidebar/SidebarViewModel.swift
Labels: Feature

#280 Feature/modify sidebar category cells/#278 #281
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
Labels: Feature

#275 Feat/written paper UI 수정/#248
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/AddCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerOfPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature, design

#287 Bug/complete button click white image bug/#285
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardResultViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
Labels: bug

#282 Feature/setting vc refactor/#274
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
Labels: Feature, refactor

#272 Feature/magnified card view UI/#265
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/BlurredViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature, design

#296 Feature/giftroom enter logic/#288
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/DatabaseManager.swift
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseMockManager.swift
  RollingPaper/RollingPaper/Models/PaperModel.swift
  RollingPaper/RollingPaper/Models/PaperPreviewModel.swift
  RollingPaper/RollingPaper/Utilities/DynamicLinks+Funcs.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftBox/GiftBoxViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/GiftPaper/GiftPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
Labels: Feature

#294 Feature/initialize view when signed out/#293
  RollingPaper/RollingPaper/Extensions/Notification.Name+Extension.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
Labels: Feature

#302 Feature/add gift button and status checking logic/#290
  RollingPaper/RollingPaper/Models/PaperModel.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature, design

#303 Feature/contextmenu bug/#292
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: bug, Feature

#301 Feature/change timeLabel implementation, add TimerTapBalloon Asset/#286
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Assets.xcassets/Interface/TimerTapBalloon/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/TimerTapBalloon/TimerTapBalloon.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Interface/TimerTapBalloon/TimerTapBalloon.imageset/TimerTapBalloon.pdf
  RollingPaper/RollingPaper/Components/TimerView.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerDiscriptionBalloon.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerOfPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: Feature, design

#306 Feature/snapshot listener added/#304
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
Labels: Feature

#308 Feature/sort by year/#305
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageCollcectionHeader.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageLength.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/GiftStorage/GiftStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
Labels: Feature, design

#310 Feature/paper card context menu/#307
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
Labels: Feature

#315 Bug/fix the button crash in CardCreate/#314
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardCreateViewController.swift
Labels: bug

#319 Feature/handle timer design/#309
  RollingPaper/RollingPaper/Components/TimerView.swift
Labels: Feature

#320 Feature/context menu modal/#316
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
Labels: bug

#325 Design/adjust design card result view/#324
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardResultViewController.swift
Labels: design

#327 Fix/delete index fix/#326
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
Labels: bug

#332 Feature/after signup events fixed/#330
  RollingPaper/RollingPaper/Extensions/Notification.Name+Extension.swift
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignUpViewController.swift
Labels: Feature

#334 Fix/blinking cell/#328
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
Labels: bug

#335 Feature/filter paper in localdb/#333
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
Labels: Feature

#337 Feature/appsettingview collection/#291
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
Labels: Feature

#339 Refactor/writtenpaperviewcontroller/#331
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
  RollingPaper/RollingPaper/Models/PaperPreviewModel.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/CardsInPaperCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Other/WrittenPaper/WrittenPaperViewModel.swift
Labels: bug, Feature, design, refactor

#340 Fix/appsettingview navigation flow error/#338
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignInViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SignUpViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
Labels: bug

#342 Feature/make view for empty content/#341
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
Labels: Feature

#345 [feat] #336 alert locate change
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
Labels: Feature

#346 Refactor/photo library using ph picker/#343
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardCreateViewController.swift
Labels: refactor

#351 Feature/add sticker block alert/#348
  RollingPaper/Pods/IRSticker-swift/IRSticker-swift/Class/IRStickerView.swift
  RollingPaper/RollingPaper/Models/TemplateEnum.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/SettingScreenViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardCreateViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/Card/CardRootViewController.swift
Labels: Feature

#352 Feature/expand timer range/#347
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Components/WarningLabel.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
Labels: Feature

#356 Fix/duplicated downloading/#354
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageLength.swift
  RollingPaper/RollingPaper/ViewControllers/Core/GiftStorage/GiftStorageViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageClosedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageLength.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageOpenedCollectionCell.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperStorage/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/GiftStorage/GiftStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperStorage/PaperStorageViewModel.swift
Labels: bug, refactor

#357 Fix/writtenpapervc vm bug fix/349
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/BlurredViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/CardsInPaperViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/TimerDiscriptionBalloon.swift
  RollingPaper/RollingPaper/ViewControllers/Other/WrittenPaper/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/Other/WrittenPaper/WrittenPaperViewModel.swift
Labels: bug, Feature, design, refactor

#361 Design/gradation on thumbnail/#360
  RollingPaper/RollingPaper/Extensions/UIView+Extensions.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTimePicker.swift
Labels: design

#364 Design/dark light mode/#344
  RollingPaper/RollingPaper/Extensions/Notification.Name+Extension.swift
  RollingPaper/RollingPaper/Models/AppSettingModels.swift
  RollingPaper/RollingPaper/SceneDelegate.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
  RollingPaper/RollingPaper/ViewControllers/SplitViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/Setting/AppSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/Core/Sidebar/SidebarViewModel.swift
Labels: Feature

#366 Design/change sidebar selection color/#365
  RollingPaper/RollingPaper/ViewControllers/Core/Sidebar/SidebarViewController.swift
Labels: design

#367 Feature/add more recent paper/#363
  RollingPaper/RollingPaper/ViewControllers/Core/PaperTemplate/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/ViewModels/Core/PaperTemplate/PaperTemplateSelectViewModel.swift
Labels: Feature

#376 Feature/Add NSPhotoLibraryAddUsageDescription/#375
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
Labels: Feature

#377 Refactor/refactor AppSettingViewController code struct/#371
  RollingPaper/RollingPaper/ViewControllers/Core/Setting/AppSettingViewController.swift
Labels: refactor
