Repository DeveloperAcademy-YOLO/ProjectYOLO, pull requests merged in 2022-10, with the labels that each got.

#13 Auth manager
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/MainViewController.swift
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Controllers/SignUpViewController.swift
  RollingPaper/RollingPaper/Info.plist
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Resources/AppDelegate.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
  RollingPaper/RollingPaper/Resources/UIApplication+Extensions.swift
  RollingPaper/RollingPaper/RollingPaper.entitlements
  RollingPaper/RollingPaper/ViewModels/SignInViewModel.swift
  RollingPaper/RollingPaper/ViewModels/SignUpViewModel.swift
Labels: Feature

#21 Feature/datamodeling/#20
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Models/CardModel.swift
  RollingPaper/RollingPaper/Models/PaperModel.swift
  RollingPaper/RollingPaper/Models/TemplateEnum.swift
  RollingPaper/RollingPaper/Models/TemplateModel.swift
  RollingPaper/RollingPaper/Models/UserModel.swift
  RollingPaper/RollingPaper/Resources/UIColor+Extensions.swift
Labels: Feature

#24 Feature/localdatabasemanager/#22
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseManager.swift
  RollingPaper/RollingPaper/Managers/PaperModelFileManager.swift
Labels: Feature

#30 Feature/select paper template/#19
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_grid.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_grid.imageset/thumbnail_grid.jpg
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_halloween.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_halloween.imageset/thumbnail_halloween.jpg
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_sunrise.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_sunrise.imageset/thumbnail_sunrise.jpg
  RollingPaper/RollingPaper/Controllers/TemplateSelectViewController.swift
  RollingPaper/RollingPaper/Models/TemplateEnum.swift
  RollingPaper/RollingPaper/Models/TemplateModel.swift
  RollingPaper/RollingPaper/ViewModels/TemplateSelectViewModel.swift
Labels: Feature

#35 Feature/localdatabasemanagerfixed/#34
  RollingPaper/Pods/Pods.xcodeproj/xcshareddata/xcschemes/SnapKit.xcscheme
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseManager.swift
  RollingPaper/RollingPaper/Managers/PaperModelFileManager.swift
Labels: Feature

#41 Feature/localdatamockdatabasemanager/#40
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/LocalDatabaseMockManager.swift
Labels: Feature

#43 Feature/set room/#33
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SetPaperViewController.swift
  RollingPaper/RollingPaper/Controllers/TemplateSelectViewController.swift
  RollingPaper/RollingPaper/ViewModels/SetPaperViewModel.swift
  RollingPaper/RollingPaper/ViewModels/TemplateSelectViewModel.swift
Labels: Feature

#39 Feature/combinecocoareinstall/#38
  RollingPaper/Podfile
  RollingPaper/Podfile.lock
  RollingPaper/Pods/CombineCocoa/LICENSE
  RollingPaper/Pods/CombineCocoa/README.md
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/AnimatedAssignSubscriber.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/CombineCocoa.h
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/CombineControlEvent.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/CombineControlProperty.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/CombineControlTarget.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/NSTextStorage+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIBarButtonItem+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIButton+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UICollectionView+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIControl+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIDatePicker+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIGestureRecognizer+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIPageControl+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIRefreshControl+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIScrollView+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UISearchBar+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UISegmentedControl+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UISlider+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UIStepper+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UISwitch+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UITableView+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UITextField+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/Controls/UITextView+Combine.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/DelegateProxy/DelegateProxy.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/DelegateProxy/DelegateProxyPublisher.swift
  RollingPaper/Pods/CombineCocoa/Sources/CombineCocoa/DelegateProxy/DelegateProxyType.swift
  RollingPaper/Pods/CombineCocoa/Sources/Runtime/ObjcDelegateProxy.m
  RollingPaper/Pods/CombineCocoa/Sources/Runtime/include/ObjcDelegateProxy.h
  RollingPaper/Pods/Manifest.lock
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa-Info.plist
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa-dummy.m
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa-prefix.pch
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa-umbrella.h
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa.debug.xcconfig
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa.modulemap
  RollingPaper/Pods/Target Support Files/CombineCocoa/CombineCocoa.release.xcconfig
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-acknowledgements.markdown
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-acknowledgements.plist
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-frameworks-Debug-input-files.xcfilelist
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-frameworks-Debug-output-files.xcfilelist
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-frameworks-Release-input-files.xcfilelist
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-frameworks-Release-output-files.xcfilelist
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper-frameworks.sh
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper.debug.xcconfig
  RollingPaper/Pods/Target Support Files/Pods-RollingPaper/Pods-RollingPaper.release.xcconfig
Labels: Feature

#49 Feature/connect view/#47
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SetPaperViewController.swift
  RollingPaper/RollingPaper/Controllers/TemplateSelectViewController.swift
  RollingPaper/RollingPaper/Resources/UINavigationController+Extensions.swift
  RollingPaper/RollingPaper/ViewModels/SetPaperViewModel.swift
  RollingPaper/RollingPaper/ViewModels/TemplateSelectViewModel.swift
Labels: Feature

#50 Feature/signupview/#40
  RollingPaper/.swiftlint.yml
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SignUpViewController.swift
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/Resources/AppDelegate.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
  RollingPaper/RollingPaper/ViewModels/SignUpViewModel.swift
  RollingPaper/RollingPaper/Views/SignUpTextField.swift
Labels: Feature

#53 Feature/signinviewrefactoring/#51
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
Labels: Feature

#61 Fix/fix AppDelegate rootView/#60
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
Labels: bug

#64 Feature/UI segmented control card step/#52,62
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
  RollingPaper/RollingPaper/ViewModels/CardBackgroundViewModel.swift
Labels: Feature

#72 Docs/Add Design Issue Template/#71
  .github/ISSUE_TEMPLATE/design-request.md
Labels: documentation

#68 Feature/authmanager profile update funcs/#66
  RollingPaper/RollingPaper/Info.plist
  RollingPaper/RollingPaper/Managers/DatabaseManager.swift
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/Managers/FirebaseStorageManager.swift
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseMockManager.swift
  RollingPaper/RollingPaper/Managers/PaperModelFileManager.swift
  RollingPaper/RollingPaper/Resources/AppDelegate.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
  RollingPaper/RollingPaper/ViewModels/SignUpViewModel.swift
Labels: Feature

#70 Feature/sidebar userinfo/#46
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/ViewModels/SidebarViewModel.swift
Labels: Feature

#79 Feature/download preview/#55
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperTemplateSelectViewModel.swift
Labels: Feature

#80 Feature/localstoragemanager/#74
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/LcalStorageManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
Labels: Feature

#81 Design/sidebar layout/#73
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
  RollingPaper/RollingPaper/Resources/UIColor+Extensions.swift
Labels: design

#84 Feature/localpushnotification/#83
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/LocalStorageManager.swift
  RollingPaper/RollingPaper/Resources/AppDelegate.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
  RollingPaper/RollingPaper/Resources/UNUserNotificationCenter+Extensions.swift
Labels: Feature

#85 Feature/nscachemanager/#82
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Managers/LocalDatabaseMockManager.swift
  RollingPaper/RollingPaper/Managers/NSCacheManager.swift
  RollingPaper/RollingPaper/Models/CardModel.swift
Labels: Feature

#89 Feature/add data control in paper storage/#87
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/Resources/AppDelegate.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
Labels: Feature

#90 Feature/add category selection effects/#45
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Models/CategoryModel.swift
Labels: Feature

#91 Feature/written paper view/#10
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/Pods/Pods.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/CustomUIComponents/UILabel+Padding.swift
  RollingPaper/RollingPaper/Resources/UIButton+Extensions.swift
Labels: Feature

#103 [docs] #102 add refactoring issue template
  .github/ISSUE_TEMPLATE/refactor-request.md
Labels: documentation

#107 Feature/writtenpaperview navigation bar items/#105
  .github/auto_assign.yml
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Resources/AppDelegate.swift
  RollingPaper/RollingPaper/Resources/UIImage+Extension.swift
Labels: Feature

#96 [feat] #94 connect navigation flow
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
Labels: Feature

#100 Feature/card data send/#69
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/first_step_icon 1.svg
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/first_step_icon 2.svg
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/first_step_icon.svg
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/second_step_icon 1.svg
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/second_step_icon 2.svg
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/second_step_icon.svg
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardResultViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/CardViewModel.swift
Labels: Feature

#116 Fix/default user info view/#108
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
Labels: bug

#115 Design/paper setting view design/#95
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_halloween_detail.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/thumbnail_halloween_detail.imageset/thumbnail_halloween_detail.jpg
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
  RollingPaper/RollingPaper/Managers/SplitViewManager.swift
  RollingPaper/RollingPaper/Models/PaperPreviewModel.swift
  RollingPaper/RollingPaper/Models/TemplateEnum.swift
  RollingPaper/RollingPaper/Models/TemplateModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperTemplateSelectViewModel.swift
Labels: design

#121 Feature/written paper viewmodel/#109
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseMockManager.swift
  RollingPaper/RollingPaper/Models/PaperModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
Labels: bug, Feature

#123 Design/adjust hi fi card part/#111
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Blood.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Blood.imageset/Halloween_Blood 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Blood.imageset/Halloween_Blood 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Blood.imageset/Halloween_Blood.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Ghost2.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Ghost2.imageset/Halloween_Ghost2 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Ghost2.imageset/Halloween_Ghost2 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Ghost2.imageset/Halloween_Ghost2.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Hat.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Hat.imageset/Halloween_Hat 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Hat.imageset/Halloween_Hat 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Hat.imageset/Halloween_Hat.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Pumpkin2.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Pumpkin2.imageset/Halloween_Pumpkin2 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Pumpkin2.imageset/Halloween_Pumpkin2 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Halloween_Pumpkin2.imageset/Halloween_Pumpkin2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Rectangle_black 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Rectangle_black 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_black.imageset/Rectangle_black.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Rectangle_light_pumpkin 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Rectangle_light_pumpkin 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_light_pumpkin.imageset/Rectangle_light_pumpkin.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Rectangle_pumpkin 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Rectangle_pumpkin 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_pumpkin.imageset/Rectangle_pumpkin.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Rectangle_red 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Rectangle_red 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_red.imageset/Rectangle_red.png
  RollingPaper/RollingPaper/Assets.xcassets/StickerToogleOff.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/StickerToogleOff.imageset/StickerToogleOff.svg
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/first_step_icon 1.svg
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/first_step_icon 2.svg
  RollingPaper/RollingPaper/Assets.xcassets/first_step_icon.imageset/first_step_icon.svg
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/second_step_icon 1.svg
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/second_step_icon 2.svg
  RollingPaper/RollingPaper/Assets.xcassets/second_step_icon.imageset/second_step_icon.svg
  RollingPaper/RollingPaper/Assets.xcassets/stickerToogleOn.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/stickerToogleOn.imageset/stickerToogle.svg
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardResultViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
  RollingPaper/RollingPaper/ViewModels/CardViewModel.swift
Labels: bug, design

#130 [but] #129 fix No_Show PencilKit When comback take photo
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/CameraCustomPicker.swift
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
Labels: bug

#132 Design/paper storage view hifi/#131
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
Labels: design

#133 Feature/signupinview refact/#128
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Controllers/SignUpViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
  RollingPaper/RollingPaper/Views/SignUpTextField.swift
Labels: Feature

#135 Design/sidebar design layout/#119
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
Labels: Feature

#138 Fix/Fix SplitView Navigation Control Logic/#124 #110
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SettingScreenViewController.swift
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Resources/Notification.Name+Extension.swift
Labels: bug, refactor

#139 Feature/add apis on written paper viewmodel/#126
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
Labels: Feature

#143 [Hotfix] #142 Bug Issue Template Auto Labeling
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug

#144 [feat] #101 Add CardViewModel logic Complete!
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardResultViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/CardViewModel.swift
Labels: Feature

#146 Fix/SplitView Controller Secondary View navigation error/#141
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
Labels: bug

#149 [fix] #147 fix WrittenPaperView Navigation
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
Labels: bug

#151 [refactoring] #148 signInView dismiss fixed
  RollingPaper/RollingPaper/Controllers/SettingScreenViewController.swift
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Controllers/SignUpViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
  RollingPaper/RollingPaper/ViewModels/SignInViewModel.swift
  RollingPaper/RollingPaper/ViewModels/SignUpViewModel.swift
Labels: Feature

#157 [feat] #153 Add Alert in CardRootView Back Button
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
Labels: Feature

#155 Feat/writtenpaper add card and refactor/#145
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardResultViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
  RollingPaper/RollingPaper/Controllers/MagnifiedCardViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Managers/FirestoreManager.swift
  RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
  RollingPaper/RollingPaper/Models/PaperPreviewModel.swift
  RollingPaper/RollingPaper/ViewModels/CardViewModel.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
Labels: Feature, refactor

#159 [feat] #154 Add alert when createing Pater
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
Labels: Feature

#160 [feat] #156 make alert button
  RollingPaper/RollingPaper/Controllers/SettingScreenViewController.swift
Labels: Feature

#164 Fix/NavigationLogic Typing Error/#163
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
Labels: bug

#168 Feature/authmanager userprofileimage/#165
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
  RollingPaper/RollingPaper/ViewModels/SettingScreenViewModel.swift
  RollingPaper/RollingPaper/ViewModels/SidebarViewModel.swift
Labels: Feature

#170 [feat] #169 run on real iPad device
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
Labels: Feature

#176 Design/userinfo layout/#173
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
Labels: design

#177 Feature/signinupview logic/#174
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Controllers/SignUpViewController.swift
  RollingPaper/RollingPaper/Views/SignUpTextField.swift
Labels: Feature

#182 Fix/index error in paper storage/#181
  RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
  RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
Labels: bug

#183 [feat] #166 Add PaperTemplete Data To Step1, Step2
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Models/TemplateEnum.swift
  RollingPaper/RollingPaper/Models/TemplateModel.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
Labels: Feature

#184 [feat] #167 Block Card Create Abuse User
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Rectangle_default 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Rectangle_default 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_default.imageset/Rectangle_default.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Contents.json
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Rectangle 1.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Rectangle 2.png
  RollingPaper/RollingPaper/Assets.xcassets/Rectangle_white.imageset/Rectangle.png
  RollingPaper/RollingPaper/Controllers/CardBackgroundViewController.swift
  RollingPaper/RollingPaper/Controllers/CardPencilKitViewController.swift
  RollingPaper/RollingPaper/Controllers/CardRootViewController.swift
Labels: Feature

#186 Feature/profile authority/#178
  RollingPaper/RollingPaper/Controllers/SettingScreenViewController.swift
Labels: Feature

#185 Refactor/deeplink refactoring/#179
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Resources/DynamicLinks+Funcs.swift
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
Labels: refactor

#188 Feat/set correct data manager/#175
  RollingPaper/RollingPaper/Controllers/SignInViewController.swift
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/Models/PaperModel.swift
  RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
Labels: bug, Feature, refactor

#190 [refactor] #180 refactor Notification logic
  RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
  RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
  RollingPaper/RollingPaper/Controllers/SplitViewController.swift
Labels: refactor

#193 Refacotring/deep link refact/#192
  RollingPaper/RollingPaper/Resources/SceneDelegate.swift
Labels: refactor

#196 [fix] #195 fix present share sheet logic
  RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper.xcodeproj/project.pbxproj
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
Labels: bug

#198 [fix] #197 fix presenting link share sheet logic
  RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
  RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
Labels: bug
